site_name: Chisel
repo_url: https://github.com/your-org/chisel
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - toc.integrate
    - content.code.annotate
    - content.action.edit

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - literate-nav

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

nav:
  - Home: index.md
  - Components:
      - Parsers: components/parsers.md
      - Tokenizers: components/tokenizers.md
      - Labelers: components/labelers.md
      - Chunkers: components/chunkers.md
      - Aligners: components/aligners.md
      - Validators: components/validators.md
      - Formatters: components/formatters.md
      - Models: components/models.md
  - Examples:
      - CoNLL: examples/conll.md
      - NCBI: examples/ncbi.md
      - JSON: examples/json.md